name: Deploy App Service and Application

on: push

jobs:
     
  deploy-application:
    runs-on: windows-latest
    steps:
  
    - name: Log in with Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    # Deploy to Azure Web apps
    - name: Deploy Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'cll-demoappgh' # The name of the web app
        slot-name: 'production'
        package: . # The name of the output location
